import type { Employee } from './types';

export const sampleData: Employee[] = [
  {
    id: 1,
    name: 'John Doe',
    position: 'Senior Developer',
    department: 'Engineering',
    salary: 85000,
    status: 'active',
    joinDate: '2022-01-15',
    performance: 92,
    skills: ['React', 'TypeScript', 'Node.js'],
  },
  {
    id: 2,
    name: 'Jane Smith',
    position: 'Product Manager',
    department: 'Product',
    salary: 95000,
    status: 'active',
    joinDate: '2021-08-20',
    performance: 88,
    skills: ['Strategy', 'Analytics', 'Leadership'],
  },
  {
    id: 3,
    name: 'Mike Johnson',
    position: 'UI/UX Designer',
    department: 'Design',
    salary: 75000,
    status: 'pending',
    joinDate: '2023-03-10',
    performance: 85,
    skills: ['Figma', 'Adobe XD', 'Prototyping'],
  },
  {
    id: 4,
    name: 'Sarah Wilson',
    position: 'Data Analyst',
    department: 'Analytics',
    salary: 70000,
    status: 'inactive',
    joinDate: '2020-11-05',
    performance: 78,
    skills: ['Python', 'SQL', 'Tableau'],
  },
  {
    id: 5,
    name: 'David Brown',
    position: 'DevOps Engineer',
    department: 'Engineering',
    salary: 90000,
    status: 'active',
    joinDate: '2022-06-12',
    performance: 94,
    skills: ['AWS', 'Docker', 'Kubernetes'],
  },
];

